[program:quantus-mining-control]
environment=PROC_NAME="%(program_name)s",MINING_CONTROL_HOME="/opt/quantus-mining-control"
command=/opt/supervisor-scripts/quantus-mining-control.sh
directory=/opt/quantus-mining-control
autostart=true
autorestart=unexpected
startsecs=2
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
